services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/budget_flux?schema=public
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - budget-network
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_flux
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - budget-network
    depends_on:
      - db

networks:
  budget-network:
    driver: bridge

volumes:
  postgres_data:

